### PR TITLE
feat: filter checks by server type

### PR DESCRIPTION
**Pull request by chen-keinan**
this change add the ability to filter checks by server type.
the purpose is to not run checks which do not match the require server type

### CODE REVIEW

**Comment by chen-keinan** [comment]
@afdesk could you please review this PR when you have time

**Comment by afdesk** [comment]
> the purpose is to not run checks which do not match the require server type

@chen-keinan I got this issue and have created #65. I thought we should detect OS via command:
```sh
> Get-ComputerInfo -Property "os*" | Select -ExpandProperty OsProductType
```
the result will be `DomainController` or `Server`. and it allows to filter the policy. 

this code already exists: 
https://github.com/aquasecurity/windows-bench/blob/4feafb51d3e07aa940053ee0640db191fd6dfc08/shell/powershell.go#L28

but it doesn't work correctly here:
https://github.com/aquasecurity/windows-bench/blob/4feafb51d3e07aa940053ee0640db191fd6dfc08/shell/powershell.go#L48-L53

wanted to debug it better. 

maybe i missed something or misunderstood your point...

**Comment by afdesk** [comment]
I took a look again:
there is a problem here
https://github.com/aquasecurity/windows-bench/blob/4feafb51d3e07aa940053ee0640db191fd6dfc08/cmd/root.go#L53-L65
it seems something missed before line 60

**Comment by afdesk** [comment]
@chen-keinan oh, it seems I understand you.

there are checks by a comma-delimited list of checks, but `serverType` was missed.

**Pull request closed without merging**
